[package]
name = "flashq"
version = "0.1.0"
edition = "2024"
license = "MIT"

[features]
default = ["http"]
http = []

[dependencies]
axum = "0.8"
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
clap = { version = "4.5", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
fs4 = "0.13.1"
sysinfo = "0.37.0"

[dev-dependencies]
serde_yaml = "0.9"
jsonschema = "0.18"
uuid = { version = "1.18.0", features = ["v4"] }
tempfile = "3.13"
