[package]
name = "flashq-cluster"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
tokio = { version = "1.47.1", features = ["full"] }
tonic = { version = "0.12", features = ["transport"] }
prost = "0.13"
thiserror = "2.0"
parking_lot = "0.12"
log.workspace = true
derive_more = { version = "1.0", features = ["from", "into", "display"] }

[dev-dependencies]
tokio = { version = "1.47.1", features = ["full"] }
tempfile = "3.13"
